In [8]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime


In [9]:
df = pd.read_excel('data.xlsx')
df

Unnamed: 0    id 3 S0.1 Code ville 4 S0.2. Sexe :  5 -  Code pays  \
0              0     1             Tunis          Homme           227.0   
1              1     2             Tunis          Femme           227.0   
2              2     3             Tunis          Femme           227.0   
3              3     4              Sfax          Femme           227.0   
4              4     5             Tunis          Femme           227.0   
...          ...   ...               ...            ...             ...   
1405        1405  1406             Tunis          Femme           227.0   
1406        1406  1407             Tunis          Femme           227.0   
1407        1407  1408             Tunis          Femme           227.0   
1408        1408  1409             Tunis          Homme           227.0   
1409        1409  1410             Gabes          Homme           227.0   

     7 Date de passation du questionnaire  \
0                              14/03/2019   
1                              16/03/2019   
2                              16/03/2019   
3                              15/03/2019   
4                              17/03/2019   
...                                   ...   
1405                           23/03/2019   
1406                           23/03/2019   
1407                           22/03/2019   
1408                           23/03/2019   
1409                           23/03/2019   

      8  S1. Combien de salariés travaillent dans votre entreprise?  \
0                                                  20.0               
1                                                  11.0               
2                                                  11.0               
3                                                  10.0               
4                                                  12.0               
...                                                 ...               
1405                                               15.0               
1406                                               40.0               
1407                                               50.0               
1408                                               10.0               
1409                                               10.0               

     9 S1. Taille de l'entreprise 10  Dans quel secteur  travaillez-vous ?  \
0             2017-10-24 00:00:00                                Industrie   
1             2017-10-24 00:00:00                                 Services   
2             2017-10-24 00:00:00                                 Services   
3             2017-10-24 00:00:00                                Industrie   
4             2017-10-24 00:00:00                       Santé (Healthcare)   
...                           ...                                      ...   
1405          2017-10-24 00:00:00                        Commerce (détail)   
1406                        25-50                        Commerce (détail)   
1407                        25-50                                 Services   
1408          2017-10-24 00:00:00                                 Services   
1409          2017-10-24 00:00:00                                   Banque   

     11  S2. Votre entreprise utilise-t-elle actuellement des téléphones mobiles ?  \
0                                                   Oui                              
1                                                   Oui                              
2                                                   Oui                              
3                                                   Oui                              
4                                                   Oui                              
...                                                 ...                              
1405                                                Oui                              
1406                                                Oui                              


In [41]:
df.columns

Index(['Unnamed: 0', 'id', '3 S0.1 Code ville', '4 S0.2. Sexe :',
       '5 -  Code pays', '7 Date de passation du questionnaire',
       '8  S1. Combien de salariés travaillent dans votre entreprise?',
       '9 S1. Taille de l'entreprise',
       '10  Dans quel secteur  travaillez-vous ?',
       '11  S2. Votre entreprise utilise-t-elle actuellement des téléphones mobiles ?',
       ...
       '145 Q42.3 La justesse de votre facture',
       '146 Q43. Utilisez-vous le service de distribution de crédit centralisé pour gérer le rechargement des utilisateurs salariés ?',
       '147 Q44. Globalement la qualité du service de distribution de crédit centralisé ?',
       '148 Q45.   votre operateur principale reste le principal opérateur de votre entreprise. ?',
       '149 Q46. Pour quel autre opérateur principal changeriez-vous ?',
       '151 Q46. Pour quel autre opérateur principal changeriez-vous ?',
       '153 Prénom', '154 Nom', '155 Numéro de téléphone',
       '156 Nom de l'entre

In [42]:
list = []
for i in df.columns:
    print(df[i].name,' ',df[i].unique())
    list.append(df[i].name)

Unnamed: 0   [   0    1    2 ... 1407 1408 1409]
id   [   1    2    3 ... 1408 1409 1410]
3 S0.1 Code ville   ['Tunis' 'Sfax' nan 'Gabes' 'Sousse']
4 S0.2. Sexe :   ['Homme' 'Femme' nan]
5 -  Code pays   [227.  nan]
7 Date de passation du questionnaire   ['14/03/2019' '16/03/2019' '15/03/2019' '17/03/2019' '20/03/2019'
 '21/03/2019' '18/03/2019' '22/03/2019' '23/03/2019' '24/03/2019'
 '25/03/2019' '27/03/2019' '28/03/2019' '29/03/2019' '30/03/2019'
 '31/03/2019' datetime.datetime(2019, 1, 4, 0, 0)
 datetime.datetime(2019, 4, 4, 0, 0) datetime.datetime(2019, 3, 4, 0, 0)
 datetime.datetime(2019, 6, 4, 0, 0) datetime.datetime(2019, 5, 4, 0, 0)
 datetime.datetime(2019, 7, 4, 0, 0) datetime.datetime(2019, 3, 14, 0, 0)
 datetime.datetime(2019, 3, 16, 0, 0) datetime.datetime(2019, 3, 15, 0, 0)
 datetime.datetime(2019, 3, 17, 0, 0) datetime.datetime(2019, 3, 20, 0, 0)
 datetime.datetime(2019, 3, 21, 0, 0) datetime.datetime(2019, 3, 18, 0, 0)
 datetime.datetime(2019, 3, 22, 0, 0) datetime.datet

KeyError: '3 - [4] S0.1 Code ville'

In [12]:
#column '9 S1. Taille de l'entreprise' changing values
c="9 S1. Taille de l'entreprise"
df[c].unique()
df[c]=df[c].replace(datetime.datetime(2017, 10, 24, 0, 0),"0-24")
df[c].unique()

array(['0-24', '25-50', nan], dtype=object)

In [13]:
#column '12 - [17] S2A. Parmi ces téléphones, y a-t-il des Smartphones ?' changing values
c="12   S2A. Parmi ces téléphones, y a-t-il des Smartphones ?"
df[c].unique()
df[c]=df[c].replace('NON','Non')
df[c].unique()

array(['Oui', 'Non', nan], dtype=object)

In [15]:
c="13 S3. Etes-vous le décideur concernant ces choix ?"
df[c].unique()
df[c]=df[c].replace('NON','Non')
df[c].unique()

array(['Oui', 'Non', nan], dtype=object)

In [ ]:
#column '4 - [12] S0.2. Sexe :' changing values
df['4 - [12] S0.2. Sexe :'].unique()
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('1. Homme','Homme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('1. HOMME','Homme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('HOMME','Homme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('HOM%ME','Homme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace(0,'Homme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('2. Femme','Femme')
df['4 - [12] S0.2. Sexe :']=df['4 - [12] S0.2. Sexe :'].replace('2. FEMME','Femme')
df['4 - [12] S0.2. Sexe :'].unique()

In [17]:
#column c changing values
c='14  S4. Quels sont tous les opérateurs que votre entreprise utilise'
df[c].unique()

df[c]=df[c].replace('/ Orange /','Orange')
df[c]=df[c].replace('/ Ooredoo /','Ooredoo')
df[c]=df[c].replace('/ Tunisie Télécom /','Tunisie Telecom')
df[c]=df[c].replace('Tunisie Télécom','Tunisie Telecom')

df[c]=df[c].replace('/ Orange / Ooredoo /','Orange/Ooredoo')
df[c]=df[c].replace('Orange/Ooredoo','Orange/Ooredoo')
df[c]=df[c].replace('/ Orange / Tunisie Télécom /','Orange/Tunisie Telecom')
df[c]=df[c].replace('Orange/Tunisie Télécom','Orange/Tunisie Telecom')
df[c]=df[c].replace('Ooredoo/Tunisie Télécom','Ooredoo/Tunisie Telecom')
df[c]=df[c].replace('/ Ooredoo / Tunisie Télécom /','Ooredoo/Tunisie Telecom')

df[c]=df[c].replace('Orange/Ooredoo/Tunisie Télécom','Orange/Ooredoo/Tunisie Telecom')
df[c]=df[c].replace('/ Orange / Ooredoo / Tunisie Télécom /','Orange/Ooredoo/Tunisie Telecom')


df[c].unique()

array(['Orange/Ooredoo', 'Orange', 'Ooredoo', 'Orange/Tunisie Telecom',
       'Orange/Ooredoo/Tunisie Telecom', 'Tunisie Telecom',
       'Ooredoo/Tunisie Telecom', nan], dtype=object)

In [18]:
#column c changing values
c='21  Q01A. Recommanderiez-vous les services de téléphonie mobile de'+
'votre opérateur principal à vos collègues ou partenaire commercial ?'
df[c].unique()
df[c]=df[c].replace('1 (Ne recommanderait certainement PAS)',1)
df[c]=df[c].replace('10 (Recommanderait certainement)',10)
df[c]=df[c].replace('11 (Ne sait pas/Non applicable)',11)
df[c].unique()

array([ 6.,  5.,  3.,  1.,  4.,  8., 10.,  7.,  9., 11.,  2., nan])

In [19]:
#column c changing values
c='22  Q01B.  recommanderiez-vous Orange à un de vos proches, vos amis et votre famille ?'
df[c].unique()
df[c]=df[c].replace('10 (Recommanderait certainement)',10)
df[c].unique()

array([ 6., nan,  9.,  7.,  5.,  8., 10.])

In [20]:
#column c changing values
c='24  Q01B.  recommanderiez-vous Tunisie Telecom à un de vos proches, vos amis et votre famille ?'
df[c].unique()
df[c]=df[c].replace('1 (Ne recommanderait certainement PAS)',1)
df[c].unique()

array([nan,  5.,  6.,  1.,  7.,  8.])

In [22]:
#column c changing values
c='27 LA QUALITE DE SERVICE GLOBALE de  votre operateur principale'
df[c].unique()
df[c]=df[c].replace('1 (La plus mauvaise note)',1)
df[c]=df[c].replace('10 (La meilleure note)',10)
df[c].unique()

array([ 6.,  5.,  8.,  9.,  7.,  4.,  3.,  1., 10., nan])

In [23]:
#column c changing values
c='28 Comment évaluez-vous le COUT GLOBAL des offres et services de votre operateur principale'
df[c].unique()
df[c]=df[c].replace('1 (La plus mauvaise note)',1)
df[c]=df[c].replace('11 (Ne sait pas/Non applicable)',11)
df[c].unique()

array([ 6.,  7.,  5.,  3.,  9.,  8.,  4.,  2.,  1., 11., nan])

In [ ]:
#column '29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez ' changing values

df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez '].unique()
df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez ']=df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez '].replace('10 (La meilleure note)',10)
df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez ']=df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez '].replace('11 (Ne sait pas/Non applicable)',11)
df['29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez '].unique()

In [ ]:
#column '30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance' changing values

df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance'].unique()
df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance']=df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance'].replace("1 (Pas du tout d'accord)",1)
df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance']=df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance'].replace("10 (Tout à fait d'accord)",10)
df['30 - [38] Q04.1 C’est un opérateur qui m’inspire confiance'].unique()

In [ ]:
#column '31 - [39] Q04.2 C’est un opérateur qui contribue à simplifier la vie de ses clients entreprise' changing values
c="31 - [39] Q04.2 C’est un opérateur qui contribue à simplifier la vie de ses clients entreprise"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c].unique()

In [ ]:
#column '32 - [40] Q04.3 C’est un opérateur qui écoute ses clients et comprend ce qu’ils veulent' changing values
c="32 - [40] Q04.3 C’est un opérateur qui écoute ses clients et comprend ce qu’ils veulent"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c].unique()

In [ ]:
#column '33 - [41] Q04.4 C’est un opérateur qui récompense la fidélité des clients entreprise' changing values
c="33 - [41] Q04.4 C’est un opérateur qui récompense la fidélité des clients entreprise"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c].unique()

In [ ]:
#column '34 - [42] Q04.5 C’est un opérateur qui résout mes problèmes lorsque c’est  nécessaire' changing values
c="34 - [42] Q04.5 C’est un opérateur qui résout mes problèmes lorsque c’est  nécessaire"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

In [ ]:
#column '35 - [43] Q04.6 Je me sens apprécié en tant que client entreprise' changing values
c="35 - [43] Q04.6 Je me sens apprécié en tant que client entreprise"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c].unique()

In [ ]:
#column '36 - [44] Q04.7 C’est un opérateur qui me propose des offres et services qui me sont essentiels' changing values
c="36 - [44] Q04.7 C’est un opérateur qui me propose des offres et services qui me sont essentiels"
df[c].unique()
df[c]=df[c].replace("1 (Pas du tout d'accord)",1)
df[c]=df[c].replace("10 (Tout à fait d'accord)",10)
df[c].unique()

In [ ]:
#column '37 - [45] Q05. Connaissez-vous les offres entreprises de votre opérateur ?' changing values
c="37 - [45] Q05. Connaissez-vous les offres entreprises de votre opérateur ?"
df[c].unique()
df[c]=df[c].replace("1. Oui",'Oui')
df[c]=df[c].replace("2. Non",'Non')
df[c].unique()

In [ ]:
#column '38 - [46] Q05A.1 … cherché des informations sur l’opérateur de votre entreprise ou ses offres' changing values
c="38 - [46] Q05A.1 … cherché des informations sur l’opérateur de votre entreprise ou ses offres"
df[c].unique()
df[c]=df[c].replace("OUI","Oui")
df[c]=df[c].replace("NON","Non")
df[c].unique()

In [ ]:
#column '39 - [47] Q05A.2 … reçu des informations de la part de cet opérateur (par exemple via des publicités, par courrier, SMS, etc)' changing values
c="39 - [47] Q05A.2 … reçu des informations de la part de cet opérateur (par exemple via des publicités, par courrier, SMS, etc)"
df[c].unique()
df[c]=df[c].replace("OUI","Oui")
df[c]=df[c].replace("NON","Non")
df[c].unique()

In [ ]:
#column '44 - [215] Q06.1 La facilité à trouver les informations que vous recherchiez, quel que soit le moyen (Internet,boutique, etc.)' changing values
c="44 - [215] Q06.1 La facilité à trouver les informations que vous recherchiez, quel que soit le moyen (Internet,boutique, etc.)"
df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)

df[c].unique()

In [ ]:
#column '45 - [217] Q06.2 La facilité à comprendre ces informations' changing values
c="45 - [217] Q06.2 La facilité à comprendre ces informations"
df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)

df[c].unique()

In [24]:
#column '46 Q07A. qu’avez-vous fait dans les 12 derniers mois :' changing values
c="46 Q07A. qu’avez-vous fait dans les 12 derniers mois :"
df[c].unique()
df[c]=df[c].replace("/ 4.	Aucun /","4.Aucun")
df[c]=df[c].replace("/ 2.	Résilié un contrat ou abonnement /","2.Résilié un contrat ou abonnement")
df[c]=df[c].replace("/ 1.	Signé un contrat avec votre opérateur principal pour la première fois /","1.Signé un contrat avec votre opérateur principal pour la première fois")
df[c]=df[c].replace("/ 1.	Signé un contrat avec votre opérateur principal pour la première fois / 2.	Résilié un contrat ou abonnement / 3.	Vous avez reçu une visite d’un commercial sans besoin particulier de votre part /","1.Signé un contrat avec votre opérateur principal pour la première fois/2.Résilié un contrat ou abonnement/3.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part")
df[c]=df[c].replace("/ 3.	Vous avez reçu une visite d’un commercial sans besoin particulier de votre part /","3.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part")
df[c]=df[c].replace("/ 1.	Signé un contrat avec votre opérateur principal pour la première fois / 2.	Résilié un contrat ou abonnement /","1.Signé un contrat avec votre opérateur principal pour la première fois/2.Résilié un contrat ou abonnement")
df[c]=df[c].replace("3.","3.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part")
df[c]=df[c].replace("Aucun","4.Aucun")
df[c]=df[c].replace("4.","4.Aucun")
df[c]=df[c].replace("4.Aucun ","4.Aucun")
df[c]=df[c].replace(7,"4.Aucun")
df[c].unique()

array(['4.Aucun', nan, '2.Résilié un contrat ou abonnement',
       '1.Signé un contrat avec votre opérateur principal pour la première fois',
       '1.Signé un contrat avec votre opérateur principal pour la première fois/2.Résilié un contrat ou abonnement/3.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part',
       '3.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part',
       '1.Signé un contrat avec votre opérateur principal pour la première fois/2.Résilié un contrat ou abonnement'],
      dtype=object)

In [25]:
#column '47 Q07B. Pour cette démarche, avez-vous…' changing values
c="47 Q07B. Pour cette démarche, avez-vous…"
df[c].unique()
df[c]=df[c].replace("/ 2.	Eté en boutique / agence /","2.Eté en boutique/agence")
df[c]=df[c].replace("/ 1.	Reçu la visite d’un commercial /","1.Reçu la visite d’un commercial")
df[c]=df[c].replace("/ 1.	Reçu la visite d’un commercial / 2.	Eté en boutique / agence /","1.Reçu la visite d’un commercial/2.Eté en boutique/agence")
df[c]=df[c].replace("/ 3.	Aucun /","3.Aucun")
df[c]=df[c].replace("Non","3.Aucun")
df[c]=df[c].replace("1.Reçu la visite d’un commercial","1.Reçu la visite d’un commercial")
df[c]=df[c].replace(8,"2.Eté en boutique/agence ")
df[c]=df[c].replace("4.","3.Aucun")
df[c]=df[c].replace("1.Reçu la visite d’un commercial/2.Eté en boutique / agence","1.Reçu la visite d’un commercial/2.Eté en boutique/agence")
df[c]=df[c].replace("Aucun","3.Aucun")
df[c]=df[c].replace("1.Aucun","1.Reçu la visite d’un commercial")
df[c]=df[c].replace("2.Aucun","2.Eté en boutique/agence")
df[c]=df[c].replace("Eté en boutique / agence","2.Eté en boutique/agence")
df[c]=df[c].replace("2.Vous avez reçu une visite d’un commercial sans besoin particulier de votre part","1.Reçu la visite d’un commercial")
df[c].unique()

array([nan, '2.Eté en boutique/agence',
       '1.Reçu la visite d’un commercial',
       '1.Reçu la visite d’un commercial/2.Eté en boutique/agence',
       '3.Aucun', '2.Eté en boutique / agence',
       '2.Eté en boutique/agence '], dtype=object)

In [26]:
#column '48  Q08.Globalement comment évaluez-vous la visite de ce commercial?' changing values
c="48  Q08.Globalement comment évaluez-vous la visite de ce commercial?"
df[c].unique()
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c].unique()

array([nan,  6.,  9.,  7.,  8.,  3., 10.,  5.])

In [27]:
#column '51 Q10.2 la compréhension de votre demande par le commercial' changing values
c="51 Q10.2 la compréhension de votre demande par le commercial"
df[c].unique()
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c].unique()

array([nan,  6.,  9.,  2.,  5.,  8., 10.,  7.])

In [28]:
#column '53 Q11.1 L’accueil privilégié en tant que client entreprise' changing values
c="53 Q11.1 L’accueil privilégié en tant que client entreprise"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  9.,  7.,  5.,  6.,  1.,  8.])

In [29]:
#column '54 Q11.2 Le temps d’attente avant de pouvoir parler à un commercial' changing values
c="54 Q11.2 Le temps d’attente avant de pouvoir parler à un commercial"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  8.,  4.,  7.,  5.,  1.,  6.])

In [30]:
#column '55 Q11.3 L’accueil, l’amabilité du personnel de la boutique / l’agence à votre arrivée' changing values
c="55 Q11.3 L’accueil, l’amabilité du personnel de la boutique / l’agence à votre arrivée"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  9.,  6.,  8.,  4.,  5.,  1.,  7.])

In [31]:
#column '56  Q11.8 La façon dont on vous a aidé à occuper votre temps en attendant d’être pris(e) en charge par un commercial' changing values
c="56  Q11.8 La façon dont on vous a aidé à occuper votre temps en attendant d’être pris(e) en charge par un commercial"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  9.,  2.,  7.,  5.,  6.,  1.,  8.])

In [32]:
#column '57  Q11.4 La compréhension de votre demande par le commercial' changing values
c="57  Q11.4 La compréhension de votre demande par le commercial"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  9.,  2.,  7.,  5.,  6.,  1.,  8.])

In [33]:
#column '58 Q11.5 La réponse ou la proposition qui vous a été faite par le commercial' changing values
c="58 Q11.5 La réponse ou la proposition qui vous a été faite par le commercial"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  9.,  2.,  7.,  4.,  5.,  1.,  6.,  8.])

In [34]:
#column '59 Q11.7 globalement votre satisfaction en sortant de ce point de vente' changing values
c="59 Q11.7 globalement votre satisfaction en sortant de ce point de vente"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([nan,  8.,  1.,  4.,  6.,  7.,  5.])

In [35]:
#column '60 La capacité de  votre operateur principale à proposer des offres qui correspondent aux besoins de votre entreprise' changing values
c="60 La capacité de  votre operateur principale à proposer des offres qui correspondent aux besoins de votre entreprise"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([ 8., nan,  5.,  1.,  7.,  3.,  6.,  9.,  4.])

In [36]:
#column '61   Q12.2 La clarté des tarifs à destination des entreprises' changing values
c="61   Q12.2 La clarté des tarifs à destination des entreprises"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([ 8., nan,  6.,  4.,  1.,  7.,  9.,  5.,  3.,  2.])

In [37]:
#column '62 Q12.3 La capacité de votre operateur principale à proposer aux entreprises des offres/services différentes de ses concurrents' changing values
c="62 Q12.3 La capacité de votre operateur principale à proposer aux entreprises des offres/services différentes de ses concurrents"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c].unique()

array([ 8., nan,  5.,  3.,  1.,  7.,  6.,  9.,  4.])

In [38]:
#column '63 Q12.4 Sa capacité à proposer des offres innovantes' changing values
c="63 Q12.4 Sa capacité à proposer des offres innovantes"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([ 8., nan,  5.,  4.,  1.,  7., 10.,  3.,  6.,  9., 11.])

In [39]:
#column '64 Q13. Globalement la mise en service de vos offres et services achetés chez votre opérateur?' changing values
c="64 Q13. Globalement la mise en service de vos offres et services achetés chez votre opérateur?"
df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([ 7., nan,  5.,  1.,  8.,  9.,  6.,  2.,  4.,  3., 10.])

In [40]:
#column '65  Q14. Globalement comment évaluez-vous la qualité du réseau de votre opérateur ? ' changing values
c="65  Q14. Globalement comment évaluez-vous la qualité du réseau de votre opérateur ? "

df.iloc[0:,61].unique()
df.iloc[0:,61]=df.iloc[0:,61].replace("1 (La mauvaise note)",1)
df.iloc[0:,61]=df.iloc[0:,61].replace("10 (La meilleure note)",10)
df.iloc[0:,61]=df.iloc[0:,61].replace("11 (Ne sait pas/ Non applicable)",11)
df.iloc[0:,61].unique()

array([ 7., nan,  5.,  8.,  9., 10.,  6.,  1.,  3.,  4.])

In [ ]:

#column '66 -  Q15. Arrivez-vous à passer votre appel dès la première tentative ? ' changing values
c="66 -  Q15. Arrivez-vous à passer votre appel dès la première tentative ? "

df[c].unique()
df[c]=df[c].replace("2.	Rarement","Rarement")
df[c]=df[c].replace("2.","Rarement")
df[c]=df[c].replace("1.","Jamais")
df[c]=df[c].replace("1.	Jamais","Jamais")
df[c]=df[c].replace("3.	Souvent","Souvent")
df[c]=df[c].replace("3.","Souvent")
df[c]=df[c].replace("4.	Toujours","Toujours")
df[c]=df[c].replace("4.","Toujours")
df[c].unique()

In [ ]:
#column '68  Q16.2 La qualité de la voix ' changing values
c="68  Q16.2 La qualité de la voix "

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

In [44]:
#column '69  Q16.3 La qualité de la communication ' changing values
c="69  Q16.3 La qualité de la communication "

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([ 9., nan,  5.,  8.,  6.,  7., 10.,  1.,  4.,  3.])

In [45]:
#column '70 Q16.4 La qualité de la voix et de la communication à l’intérieur des bâtiments' changing values
c="70 Q16.4 La qualité de la voix et de la communication à l’intérieur des bâtiments"

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([ 9., nan,  5.,  8.,  7.,  6.,  3.,  1.,  4., 10.])

In [46]:
#column '71 Q16.5 La qualité de la voix et de la communication à l’extérieur des bâtiments' changing values
c="71 Q16.5 La qualité de la voix et de la communication à l’extérieur des bâtiments"

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([ 9., nan,  5.,  8.,  7.,  6.,  4., 10.,  1.,  3.])

In [47]:
#column '73 Q16B l’accompagnement de  votre operateur principale pendant ces périodes de panne de réseau ? ' changing values
c="73 Q16B l’accompagnement de  votre operateur principale pendant ces périodes de panne de réseau ? "

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  5.,  1.,  6.,  3.,  2.,  8.,  7.,  4.,  9.])

In [48]:
#column '80 facilite d'utilisation et fonctionnement de   Transfert de crédit' changing values
c="80 facilite d'utilisation et fonctionnement de   Transfert de crédit"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  6.,  1.,  5.,  9.,  3.,  4.])

In [49]:
#column '81 facilite d'utilisation et fonctionnement de Transfert Internet' changing values
c="81 facilite d'utilisation et fonctionnement de Transfert Internet"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  5.,  1.,  6.,  9.,  8.])

In [50]:
#column '82facilite d'utilisation et fonctionnement de  SOS crédit / Minute SOS/ SOS Solde' changing values
c="82facilite d'utilisation et fonctionnement de  SOS crédit / Minute SOS/ SOS Solde"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  5.,  6.,  1.,  8.,  4.,  7.])

In [51]:
#column '83  facilite d'utilisation et fonctionnement de  Orange fidélité ou Points Merci ou  Kelma' changing values
c="83  facilite d'utilisation et fonctionnement de  Orange fidélité ou Points Merci ou  Kelma"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  1.,  8.,  7.])

In [52]:
#column '84  facilite d'utilisation et fonctionnement de  Messagerie vocale' changing values
c="84  facilite d'utilisation et fonctionnement de  Messagerie vocale"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  7.,  8.,  1.,  5.])

In [53]:
#column '85 facilite d'utilisation et fonctionnement de  Appelez jusqu'à six ou Conf Call pro ou Appel en conférence' changing values
c="85 facilite d'utilisation et fonctionnement de  Appelez jusqu'à six ou Conf Call pro ou Appel en conférence"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  8.,  1.,  5., 11.])

In [54]:
#column '89 Raison pour utilise Orange money' changing values
c="89 Raison pour utilise Orange money"
df[c].unique()
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique / 3.Paiement de facture /","2.Rechargement crédit téléphonique/3.Paiement de facture")
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique /","2.Rechargement crédit téléphonique")

df[c].unique()

array([nan, '3.Paiement de facture',
       '2.Rechargement crédit téléphonique/3.Paiement de facture',
       '2.Rechargement crédit téléphonique'], dtype=object)

In [55]:
#column '90 Raison pour utilise Mobicash Ooredoo' changing values
c="90 Raison pour utilise Mobicash Ooredoo"

df[c].unique()
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique / 3.Paiement de facture /","2.Rechargement crédit téléphonique/3.Paiement de facture")
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique /","2.Rechargement crédit téléphonique")

df[c].unique()

array([nan, '2.Rechargement crédit téléphonique', '3.Paiement de facture',
       '2.Rechargement crédit téléphonique/3.Paiement de facture'],
      dtype=object)

In [56]:
#column '91 Raison pour utilise Mdinar TT' changing values
c="91 Raison pour utilise Mdinar TT"

df[c].unique()
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique / 3.Paiement de facture /","2.Rechargement crédit téléphonique/3.Paiement de facture")
df[c]=df[c].replace("/ 3.Paiement de facture /","3.Paiement de facture")
df[c]=df[c].replace("/ 2.Rechargement crédit téléphonique /","2.Rechargement crédit téléphonique")

df[c].unique()

array([nan, '2.Rechargement crédit téléphonique', '3.Paiement de facture'],
      dtype=object)

In [57]:
#column '103Q20bis.1 L’accessibilité au réseau' changing values
c="103Q20bis.1 L’accessibilité au réseau"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  5.,  7.,  8.,  1.,  3.,  4.])

In [59]:
#column '104 Q20bis.2 La qualité de la voix ' changing values
c="104 Q20bis.2 La qualité de la voix "

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace('2. Ooredoo',2)
df[c]=df[c].replace('1. Orange',1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  5.,  7.,  8.,  1.,  4.,  3.,  2.])

In [60]:
#column '105 Q20bis.3 La qualité de la connexion à l’internet mobile' changing values
c="105 Q20bis.3 La qualité de la connexion à l’internet mobile"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan, 11.,  5.,  7.,  8.,  6.,  2.,  4.])

In [61]:
#column '106 Q20bis.4 L’information transmise par votre opérateur sur les coûts d’utilisation du service roaming ' changing values
c="106 Q20bis.4 L’information transmise par votre opérateur sur les coûts d’utilisation du service roaming "

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  5.,  7.,  6.,  8.,  2.,  4.,  3., 11.])

In [62]:
#column '107 Q20bis.5 Le coût du service roaming' changing values
c="107 Q20bis.5 Le coût du service roaming"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan, 11.,  1.,  7.,  3.,  5.,  4.,  8.,  2.,  6.])

In [64]:
#column '110 Q25.1  l’accessibilité au réseau Internet mobile de votre opérateur' changing values
c="110 Q25.1  l’accessibilité au réseau Internet mobile de votre opérateur"

df[c].unique()
df[c]=df[c].replace("1 ( la plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  5.,  6.,  8.,  4.,  9.,  1.,  3., 10.,  2.])

In [66]:
#column '112  Q26 Le rapport qualité-prix de l’offre Internet mobile' changing values
c="112  Q26 Le rapport qualité-prix de l’offre Internet mobile"

df[c].unique()
df[c]=df[c].replace("1 ( la plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  4.,  7.,  5.,  9.,  8., 10.,  3.,  1.,  2.])

In [67]:
#column '111Q25.2 La vitesse de navigation et de chargement des pages sur Internet mobile de votre opérateur' changing values
c="111Q25.2 La vitesse de navigation et de chargement des pages sur Internet mobile de votre opérateur"

df[c].unique()
df[c]=df[c].replace("1 ( la plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  5.,  7.,  9.,  8.,  3.,  1.,  4., 10.,  2.])

In [68]:
#column '112  Q26 Le rapport qualité-prix de l’offre Internet mobile' changing values
c="112  Q26 Le rapport qualité-prix de l’offre Internet mobile"

df[c].unique()
df[c]=df[c].replace("1 ( la plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  6.,  4.,  7.,  5.,  9.,  8., 10.,  3.,  1.,  2.])

In [70]:
#column '113  Q27otre entreprise envisage-t-elle de souscrire une offre Internet mobile pour un ou plusieurs salariés ?' changing values
c="113  Q27otre entreprise envisage-t-elle de souscrire une offre Internet mobile pour un ou plusieurs salariés ?"

df[c].unique()
df[c]=df[c].replace("5.	Ne sait pas","5.Ne sait pas")
df[c]=df[c].replace("3.	Non, probablement pas","3.Non, probablement pas")
df[c]=df[c].replace("4.	Non, certainement pas","4.Non, certainement pas")
df[c]=df[c].replace("2.	Oui, probablement","2.Oui, probablement")
df[c]=df[c].replace("1.	Oui, certainement","1.Oui, certainement")
df[c]=df[c].replace("5.Oui, probablement","5.Ne sait pas")

df[c].unique()

array(['5.Ne sait pas', nan, '3.Non, probablement pas',
       '4.Non, certainement pas', '2.Oui, probablement',
       '1.Oui, certainement'], dtype=object)

In [75]:
#column '117Q31. Et pour cette démarche vous avez : ' changing values
c="117Q31. Et pour cette démarche vous avez : "

df[c].unique()
df[c]=df[c].replace("/ 2.\tAppelé un numéro service client / 5.\tVous êtes allés sur le site internet de votre opérateur / 6.\tVous avez contacté votre opérateur via Facebook, Twitter, etc /","2.Appelé un numéro service client/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc")
df[c]=df[c].replace("/ 1.\tAppelé un commercial / 3.\tVous êtes allés dans une boutique / agence / 5.\tVous êtes allés sur le site internet de votre opérateur / 6.\tVous avez contacté votre opérateur via Facebook, Twitter, etc /","1.Appelé un commercial/3.Vous êtes allés dans une boutique / agence/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc")
df[c]=df[c].replace("/ 2.\tAppelé un numéro service client /","2.Appelé un numéro service client")
df[c]=df[c].replace("/ 1.\tAppelé un commercial /","1.Appelé un commercial")
df[c]=df[c].replace("/ 1.\tAppelé un commercial / 2.\tAppelé un numéro service client / 3.\tVous êtes allés dans une boutique / agence /","1.Appelé un commercial/2.Appelé un numéro service client/3.Vous êtes allés dans une boutique / agence")
df[c]=df[c].replace("2.\tAppelé un numéro service client / 5.\tVous êtes allés sur le site internet de votre opérateur / 6.\tVous avez contacté votre opérateur via Facebook, Twitter, etc /","2.Appelé un numéro service client/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc")
df[c]=df[c].replace("/ 1.\tAppelé un commercial / 2.\tAppelé un numéro service client / 4.\tVous êtes allés chez un distributeur /","1.Appelé un commercial/2.Appelé un numéro service client/4.Vous êtes allés chez un distributeur")
df[c]=df[c].replace("/ 1.\tAppelé un commercial / 2.\tAppelé un numéro service client /","1.Appelé un commercial/2.Appelé un numéro service client")
df[c]=df[c].replace("/ 2.\tAppelé un numéro service client / 3.\tVous êtes allés dans une boutique / agence /","2.Appelé un numéro service client/3.Vous êtes allés dans une boutique / agenc")
df[c]=df[c].replace("/ 2.\tAppelé un numéro service client /","2.Appelé un numéro service client")
df[c]=df[c].replace("/ 1.\tAppelé un commercial / 2.\tAppelé un numéro service client / 5.\tVous êtes allés sur le site internet de votre opérateur / 6.\tVous avez contacté votre opérateur via Facebook, Twitter, etc /","1.Appelé un commercial/2.Appelé un numéro service client/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc")
df[c].unique()

array([nan, '2.Appelé un numéro service client', '1.Appelé un commercial',
       '1.Appelé un commercial/2.Appelé un numéro service client/3.Vous êtes allés dans une boutique / agence',
       '2.Appelé un numéro service client/3.Vous êtes allés dans une boutique / agenc',
       '3.Vous êtes allés dans une boutique / agence',
       '1.Appelé un commercial/2.Appelé un numéro service client',
       '2.Appelé un numéro service client/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc',
       '1.Appelé un commercial/3.Vous êtes allés dans une boutique / agence/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous avez contacté votre opérateur via Facebook, Twitter, etc',
       '1.Appelé un commercial/2.Appelé un numéro service client/4.Vous êtes allés chez un distributeur',
       '1.Appelé un commercial/2.Appelé un numéro service client/5.Vous êtes allés sur le site internet de votre opérateur/6.Vous a

In [77]:
#column '118  Q32.1 La compréhension de votre demande ou réclamation' changing values
c="118  Q32.1 La compréhension de votre demande ou réclamation"

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  1.,  6.,  5.,  3.,  8.,  9.])

In [78]:
#column '119  Q32.2 La rapidité de traitement de votre demande ou réclamation' changing values
c="119  Q32.2 La rapidité de traitement de votre demande ou réclamation"

df[c].unique()
df[c]=df[c].replace("1 (La mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  7.,  1.,  6.,  3.,  5.,  8.,  9.])

In [79]:
#column '120  Q33. Après cette démarche, avez-vous dû recontacter un commercial pour la même demande ou le même problème ?' changing values
c="120  Q33. Après cette démarche, avez-vous dû recontacter un commercial pour la même demande ou le même problème ?"

df[c].unique()
df[c]=df[c].replace("1.	Oui","1.Oui")
df[c]=df[c].replace("2.	Non, mon problème / ma demande était résolue","2.Non, mon problème / ma demande était résolue")
df[c]=df[c].replace("3.	Ne sait pas","3.Ne sait pas")
df[c].unique()

array([nan, '1.Oui', '2.Non, mon problème / ma demande était résolue',
       '3.Ne sait pas'], dtype=object)

In [80]:
#column '121 Q34. Vous avez appelé le service client. Avez-vous réussi à parler à un conseiller ?' changing values
c="121 Q34. Vous avez appelé le service client. Avez-vous réussi à parler à un conseiller ?"

df[c].unique()
df[c]=df[c].replace("1.	Oui","1.Oui")
df[c]=df[c].replace("2.	Non","2.Non")
df[c]=df[c].replace(7,"0")
df[c].unique()

array([nan, '1.Oui', '2.Non', '0'], dtype=object)

In [82]:
#column '122 Q35.1 Le temps d’attente avant de parler à un conseiller' changing values
c="122 Q35.1 Le temps d’attente avant de parler à un conseiller"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  4.,  1.,  6.,  7.,  5.])

In [83]:
#column '123  Q35.2 L’accueil téléphonique, l’amabilité de votre interlocuteur ' changing values
c="123  Q35.2 L’accueil téléphonique, l’amabilité de votre interlocuteur "

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  9.,  1.,  7.,  6.,  5.])

In [84]:
#column '124  Q35.3 La compréhension de votre demande ou réclamation' changing values
c="124  Q35.3 La compréhension de votre demande ou réclamation"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  9.,  1.,  7.,  6.,  5.])

In [85]:
#column '125  Q35.4 La solution proposée' changing values
c="125  Q35.4 La solution proposée"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  9.,  1.,  7.,  6.,  5.])

In [86]:
#column '126 Q35.5 La résolution de votre réclamation ou demande lors de cet appel' changing values
c="126 Q35.5 La résolution de votre réclamation ou demande lors de cet appel"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  9.,  1.,  8.,  7.,  6.])

In [87]:
#column '127 Q36. Avez-vous dû rappeler le service client pour le même problème, la même demande ?' changing values
c="127 Q36. Avez-vous dû rappeler le service client pour le même problème, la même demande ?"

df[c].unique()
df[c]=df[c].replace("3.	Non","3.Non")
df[c]=df[c].replace("1.	Oui, une fois","1.Oui, une fois")
df[c]=df[c].replace("2.	Oui, plusieurs fois","2.Oui, plusieurs fois")
df[c].unique()

array([nan, '3.Non', '1.Oui, une fois', '2.Oui, plusieurs fois'],
      dtype=object)

In [88]:
#column '128 Q37.1 La compréhension de votre demande ou de votre réclamation par le commercial' changing values
c="128 Q37.1 La compréhension de votre demande ou de votre réclamation par le commercial"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  1.,  7.,  6.])

In [89]:
#column '129 Q37.2 La rapidité de traitement de votre demande ou réclamation' changing values
c="129 Q37.2 La rapidité de traitement de votre demande ou réclamation"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  1.,  6.,  7.,  8.])

In [90]:
#column '130 Q37.3 La solution qui vous a été proposée' changing values
c="130 Q37.3 La solution qui vous a été proposée"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

array([nan,  1.,  7.,  6.,  5.,  8.])

In [95]:
#column '131 Q38. Après votre visite, avez-vous dû retourner en boutique ou agence ou appeler le call center de votre opérateur pour le même problème, la même demande ?' changing values
c="131 Q38. Après votre visite, avez-vous dû retourner en boutique ou agence ou appeler le call center de votre opérateur pour le même problème, la même demande ?"

df[c].unique()
df[c]=df[c].replace("/ 1.\tOui, je suis retourné en boutique / agence / 2.\tOui, j’ai appelé le call center /",".Oui, je suis retourné en boutique / agence/2.Oui, j’ai appelé le call center")
df[c]=df[c].replace("/ 3.\tNon, mon problème était résolu /', '/ 4.\tNe sait pas /","3.Non, mon problème était résolu', '4.Ne sait pas")
df[c]=df[c].replace("/ 2.\tOui, j’ai appelé le call center /","2.Oui, j’ai appelé le call center")
df[c]=df[c].replace("/ 3.\tNon, mon problème était résolu /","3.Non, mon problème était résolu")
df[c]=df[c].replace("/ 4.\tNe sait pas /","4.Ne sait pas")
df[c]=df[c].replace(".Oui, je suis retourné en boutique / agence/2.Oui, j’ai appelé le call center","1.Oui, je suis retourné en boutique / agence/2.Oui, j’ai appelé le call center")
df[c]=df[c].replace("/ 1.\tOui, je suis retourné en boutique / agence /",'1.Oui, je suis retourné en boutique / agence')
df[c].unique()

array([nan,
       '1.Oui, je suis retourné en boutique / agence/2.Oui, j’ai appelé le call center',
       '3.Non, mon problème était résolu', '4.Ne sait pas',
       '1.Oui, je suis retourné en boutique / agence',
       '2.Oui, j’ai appelé le call center'], dtype=object)

In [97]:
#column '142Q41. Globalement le ou les systèmes de facturation proposés par votre operateur principale ?' changing values
c="142Q41. Globalement le ou les systèmes de facturation proposés par votre operateur principale ?"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas / Non applicable)",11)
df[c].unique()

array([nan,  4.,  3.,  1.,  5.,  7.,  8.,  6., 11.,  9.])

In [98]:
#column '143  Q42.1 Le délai de réception de la facture' changing values
c="143  Q42.1 Le délai de réception de la facture"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas / Non applicable)",11)
df[c].unique()

array([nan,  5.,  2.,  1.,  6.,  8.,  7.,  4., 11.,  3.,  9., 10.])

In [99]:
#column '144  Q42.2 La facilité à comprendre la facture' changing values
c="144  Q42.2 La facilité à comprendre la facture"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas / Non applicable)",11)
df[c].unique()

array([nan,  6.,  2.,  1.,  5.,  7.,  8.,  3.,  9.,  4., 11., 10.])

In [100]:
#column '145 Q42.3 La justesse de votre facture' changing values
c="145 Q42.3 La justesse de votre facture"

df[c].unique()
df[c]=df[c].replace("1 (La plus mauvaise note)",1)
df[c]=df[c].replace("10 (La meilleure note)",10)
df[c]=df[c].replace("11 (Ne sait pas / Non applicable)",11)
df[c].unique()

array([nan,  7.,  5.,  1.,  8.,  6.,  3.,  9.,  4.,  2., 11., 10.])

In [102]:
#column '146 Q43. Utilisez-vous le service de distribution de crédit centralisé pour gérer le rechargement des utilisateurs salariés ?' changing values
c="146 Q43. Utilisez-vous le service de distribution de crédit centralisé pour gérer le rechargement des utilisateurs salariés ?"

df[c].unique()
df[c]=df[c].replace("2.	Non","2.Non")
df[c]=df[c].replace("2.	Non","2.Non")
df[c]=df[c].replace("2.	Non","2.Non")
df[c]=df[c].replace("1.	Oui","1.Oui")
df[c]=df[c].replace("2.","2.Non")
df[c]=df[c].replace("2.Ne souhaite pas changer","2.Non")
df[c].unique()

array(['2.Non', nan, '1.Oui', '4.Ne souhaite pas changer'], dtype=object)

In [103]:
#column '149 Q46. Pour quel autre opérateur principal changeriez-vous ?' changing values
c="149 Q46. Pour quel autre opérateur principal changeriez-vous ?"

df[c].unique()
df[c]=df[c].replace("3.Tunisie telecom","Tunisie telecom")

df[c].unique()

array([nan, 'Tunisie telecom', 'Orange', 'Ooredoo', 'Ne sait pas',
       'Autre'], dtype=object)

In [ ]:
#column '114 - [141] Q28. Chez quel opérateur ?' changing values
c="114 - [141] Q28. Chez quel opérateur ?"

df[c].unique()
df[c]=df[c].replace("1.  Orange","Orange")
df[c]=df[c].replace("2. Ooredoo","Ooredoo")
df[c]=df[c].replace("3. Tunisie Télécom","Tunisie Telecom")
df[c]=df[c].replace("9.Autre","Autre")
df[c]=df[c].replace("3. Tunisie télécom","Tunisie Telecom")
df[c]=df[c].replace("1. Orange","Orange")
df[c]=df[c].replace("1.Orange ","Orange")
df[c]=df[c].replace("1 (La plus mauvaise note)","Orange")
df[c]=df[c].replace("3.Tunisie télécom1","Tunisie Telecom")
df[c].unique()

In [ ]:
df=df.drop(["116 - [143] Q29. Dans les 6 derniers mois, avez-vous eu besoin d’aide auprès de [V15] concernant les offres souscrites ?",
            "117 - [144] Q31. Et pour cette démarche vous avez : ",
            "118 - [145] Q32.1 La compréhension de votre demande ou réclamation",
           "119 - [146] Q32.2 La rapidité de traitement de votre demande ou réclamation",
             "120 - [147] Q33. Après cette démarche, avez-vous dû recontacter un commercial pour la même demande / le même problème ?",
             "121 - [148] Q34. Vous avez appelé le service client. Avez-vous réussi à parler à un conseiller ?",
             "122 - [150] Q35.1 …Le temps d’attente avant de parler à un conseiller",
            "123 - [151] Q35.2 …L’accueil téléphonique, l’amabilité de votre interlocuteur …",
            "124 - [152] Q35.3…La compréhension de votre demande / réclamation",
           "125 - [153] Q35.4 La solution proposée",
             "126 - [154] Q35.5 La résolution de votre réclamation / demande lors de cet appel",
             "127 - [155] Q36. Avez-vous dû rappeler le service client pour le même problème, la même demande ?",
             "128 - [157] Q37.1 La compréhension de votre demande ou de votre réclamation par le commercial",
            "131 - [156] Q38. Après votre visite, avez-vous dû retourner en boutique / agence ou appeler le call center de votre opérateur pour le même problème, la même demande ?",
            "132 - [160] Q39.1 La compréhension de votre demande",
           "133 - [161] Q39.2 La  réponse qui vous a été apportée",
             "134 - [162] Q39.3 La rapidité du traitement de votre demande",
             "135 - [163] Q39.4 La résolution de votre problème/demande grâce à ce message sur les réseaux sociaux ou cette visite sur le site Internet de l’opérateur",
             "143 - [176] Q42.1 Le délai de réception de la facture",
                      "144 - [177] Q42.2 La facilité à comprendre la facture",
                      "145 - [178] Q42.3 La justesse de votre facture",
            "146 - [175] Q43. Utilisez-vous le service de distribution de crédit centralisé pour gérer le rechargement des utilisateurs salariés ?",
            "141 - [172] Q40.6 Votre première facture vous a-t-elle été expliquée (par votre commercial ou en point de vente) ?"],axis=1)

In [ ]:
#column '148 - [180] Q45. Pour finir, dans quelle mesure est-il probable qu’au cours des 6 prochains mois, [V15] reste le principal opérateur de votre entreprise. Utilisez une échelle de 1 à 10 où 1 signifie très peu probable et 10 extrêmement probable ?' changing values
c="148 - [180] Q45. Pour finir, dans quelle mesure est-il probable qu’au cours des 6 prochains mois, [V15] reste le principal opérateur de votre entreprise. Utilisez une échelle de 1 à 10 où 1 signifie très peu probable et 10 extrêmement probable ?"

df[c].unique()
df[c]=df[c].replace("1 (Très peu probable)",1)
df[c]=df[c].replace("10 (Extrêmement probable)",10)
df[c]=df[c].replace("11 (Ne sait pas/ Non applicable)",11)
df[c].unique()

In [ ]:
#column '149 - [181] Q46. Pour quel autre opérateur principal changeriez-vous ?' changing values
c="149 - [181] Q46. Pour quel autre opérateur principal changeriez-vous ?"

df[c].unique()
df[c]=df[c].replace("1.Orange","Orange")
df[c]=df[c].replace("2.	Ooredoo","Ooredoo")
df[c]=df[c].replace("6.	Ne sait pas","Ne sait pas")
df[c]=df[c].replace("3.	Tunisie télécom","Tunisie telecom")
df[c]=df[c].replace("3.","Tunisie telecom")
df[c]=df[c].replace("2.","Ooredoo")
df[c]=df[c].replace("6.","Ne sait pas")
df[c]=df[c].replace("1.","Orange")
df[c]=df[c].replace(2,"Ooredoo")
df[c]=df[c].replace("6.Ne sait pas","Ne sait pas")
df[c]=df[c].replace("1.	Orange","Orange")
df[c]=df[c].replace("2.Ooredoo","Ooredoo")
df[c]=df[c].replace("3.Tunisie télécom","3.Tunisie telecom")
df[c]=df[c].replace("5.Autre, préciser","Autre")
df[c].unique()

In [ ]:
#column '151 - [227] Q46. Pour quel autre opérateur principal changeriez-vous ?' changing values
c="151 - [227] Q46. Pour quel autre opérateur principal changeriez-vous ?"

df[c].unique()
df[c]=df[c].replace("4.	Ne souhaite pas changer","Ne souhaite pas changer")
df[c]=df[c].replace("4.Ne souhaite pas changer","Ne souhaite pas changer")
df[c]=df[c].replace("2.","Ne souhaite pas changer")
df[c].unique()

In [ ]:
df=df.drop(["152 - [183] Q47. Suite à ce questionnaire, pour être sûr de "
+"répondre à vos attentes, acceptez-vous de transmettre votre nom et vos coordonnées avec vos réponses à votre opérateur principal ?"],axis=1)

In [ ]:
df.rename(columns={"17 - [23] S7. Pour tous les opérateurs présents dans votre entreprise, pouvez-vous indiquer quel énoncé, parmi les suivants, décrit le mieux la situation de votre entreprise ? ":"17  Pour Orange, quel énoncé décrit le mieux la situation de votre entreprise ? "})
df.rename(columns={"18 - [22] S7. Pour tous les opérateurs présents dans votre entreprise, pouvez-vous indiquer quel énoncé, parmi les suivants, décrit le mieux la situation de votre entreprise ? ":"18  Pour Ooredoo, quel énoncé décrit le mieux la situation de votre entreprise ? "})
df.rename(columns={"19 - [24] S7. Pour tous les opérateurs présents dans votre entreprise, pouvez-vous indiquer quel énoncé, parmi les suivants, décrit le mieux la situation de votre entreprise ? ":"19  Pour Tunisie Telecom, quel énoncé décrit le mieux la situation de votre entreprise ? "})

df.rename(columns={"22 - [27] Q01B. Toujours sur une échelle de 1 à 10, dans quelle mesure recommanderiez-vous vos autres opérateurs à un de vos proches, vos amis et votre famille ?":"22 recommanderiez-vous Orange à un de vos proches, vos amis et votre famille ?"})
df.rename(columns={"23 - [29] Q01B. Toujours sur une échelle de 1 à 10, dans quelle mesure recommanderiez-vous vos autres opérateurs à un de vos proches, vos amis et votre famille ?":"23 recommanderiez-vous Ooredoo à un de vos proches, vos amis et votre famille ?"})
df.rename(columns={"24 - [30] Q01B. Toujours sur une échelle de 1 à 10, dans quelle mesure recommanderiez-vous vos autres opérateurs à un de vos proches, vos amis et votre famille ?":"24 recommanderiez-vous Tunisie Telecom à un de vos proches, vos amis et votre famille ?"})

df.rename(columns={"25 - [32] A TOUS ":"25 Orange a fait quelque chose qui allait au-delà de vos attentes"})
df.rename(columns={"26 - [200] A TOUS ":"26 Orange a fait quelque chose qui n’a pas répondu à vos attentes"})
df.rename(columns={"c":"27 LA QUALITE DE SERVICE GLOBALE "})
df.rename(columns={"28 - [35] Q02. Comment évaluez-vous le COUT GLOBAL des offres et services de [V15] ?  Ce coût inclut le coût de votre/vos contrat/s, les coûts des forfaits, l’achat initial ou les coûts de renouvellement des appareils ainsi que les coûts des communications. Veuillez utiliser une échelle de 1 à 10 où 1 signifie médiocre et 10 excellent.":"28 Comment évaluez-vous le COUT GLOBAL des offres et services de votre operateur principale "})
df.rename(columns={"29 - [36] Q03.Pour résumer, sur une échelle de 1 à 10, évaluez le rapport qualité-prix, c’est-à-dire dans quelle mesure vous pensez que le prix que votre entreprise paye à votre opérateur [V15] est justifié par rapport aux services que vous recevez ":"29 le rapport qualité-prix  "})
df.rename(columns={"64 - [74] Q13. Globalement, sur une échelle de 1 à 10, comment évaluez-vous la mise en service de vos offres et services achetés chez votre opérateur (activation de la flotte mobile, prise en main des téléphones…) ?":"64  Globalement comment évaluez-vous la mise en service de vos offres et services achetés chez votre opérateur?"})


df.rename(columns={"80 - [101] Transfert de crédit":"80 facilite d'utilisation et fonctionnement de Transfert de crédit"})
df.rename(columns={"81 - [102] Transfert Internet":"81 facilite d'utilisation et fonctionnement de Transfert Internet"})
df.rename(columns={"82 - [103] SOS crédit / Minute SOS/ SOS Solde":"82 facilite d'utilisation et fonctionnement  de SOS crédit / Minute SOS/ SOS Solde"})
df.rename(columns={"83 - [104] Orange fidélité/ Points Merci/ Kelma":"83 facilite d'utilisation et fonctionnement  Orange fidélité/ Points Merci/ Kelma"})
df.rename(columns={"84 - [105] Messagerie vocale":"84 facilite d'utilisation et fonctionnement Messagerie vocale"})
df.rename(columns={"85 - [106] Appelez jusqu'à six/ Conf Call pro/ Appel en conférence":"85 facilite d'utilisation et fonctionnement Appelez jusqu'à six/ Conf Call pro/ Appel en conférence"})


df.rename(columns={"89 - [193] Orange money":"89 Raison pour utilise Orange money"})
df.rename(columns={"90 - [194] Mobicash (ooredoo)":"80 Raison pour utilise Mobicash Ooredoo"})
df.rename(columns={"91 - [195] Mdinar (TT)":"91 Raison pour utilise Mdinar TT"})
df.rename(columns={"92 - [117] Orange Money":"92 facilite d'utilisation et fonctionnement Orange Money"})
df.rename(columns={"93 - [118] Mobicash (ooredoo)":"93 facilite d'utilisation et fonctionnement Mobicash (ooredoo)"})
df.rename(columns={"94 - [119] Mdinar (TT)":"94 facilite d'utilisation et fonctionnement Mdinar (TT)"})


df.rename(columns={"101 - [126] Q18. Au cours de 12 derniers mois, avez-vous dans votre entreprise utilisé le service roaming [V15], c'est-à-dire passé ou reçu des appels ou sms ou naviguer sur Internet depuis un mobile alors qu’il se trouvait à l’étranger, et ce sans changer de carte SIM ?":"101 avez-vous dans votre entreprise utilisé le service roaming"})
df.rename(columns={"114 - [141] Q28. Chez quel opérateur ?":"114 votre entreprise envisage-t-elle de souscrire une offre Internet mobile pour un ou plusieurs salariés dans quel operateur"})
df.rename(columns={"129 - [158] Q37.2 La rapidité de traitement de votre demande / réclamation":"Globalement note commercial"})


In [108]:
df=df.fillna(-1)

In [ ]:
df.to_excel("InternalData.xlsx")